<?php
    $GLOBALS['expresiones_regulares'] = [
        // id's
        'id' => '/^[0-9]*$/',
        'id_permiso' => '/^[0-9]+$/',
        'id_metodo_pago' => '/^[0-9]+$/',
        'id_rol' => '/^[0-9]+$/',
        'id_usuario' => '/^[0-9]+$/',
        'id_usuario_delivery' => '/^[0-9]+$/',
        'id_venta' => '/^[0-9]+$/',
        'id_materia_prima' => '/^[0-9]+$/',
        'id_entrada' => '/^[0-9]+$/',
        'id_receta' => '/^[0-9]+$/',
        'id_producto' => '/^[0-9]+$/',
        'id_orden' => '/^[0-9]+$/',
        'id_producto_preparado' => '/^[0-9]+$/',
        'id_entrada_materia_prima' => '/^[0-9]+$/',
        'id_detalle_entrada_materia_prima' => '/^[0-9]+$/',
        'id_proveedor' => '/^[0-9]+$/',
        'id_unidad' => '/^[0-9]+$/',
        'id_categoria' => '/^[0-9]+$/',
        'id_mesa' => '/^[0-9]+$/',
        'id_reserva' => '/^[0-9]+$/',
        'id_pago' => '/^[0-9]+$/',
        'id_paquete' => '/^[0-9]+$/',
        'id_caja' => '/^[0-9]+$/',


        //fechas
        'fecha' => '/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/',
        'fecha_compra' => '/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/',
        'fecha_inicio' => '/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/',
        'fecha_final' => '/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/',
        'total_ventas' => '/^[0-9]+$/',
        'fecha_apertura' => '/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/',
        'fecha_cierre' => '/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/',
        'fecha_vencimiento' => '/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/',
        'fecha_bloqueo' => '/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/',

        //textos
        'nombre' => '/^[a-zA-Z ]+$/',
        'apellido' => '/^[a-zA-Z ]+$/',
        'telefono' => '/^[0-9]{10}$/',
        'email' => '/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/',
        'password' => '/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/',
        'active' => '/^[0-1]+$/',
        'session_id' => '/^[a-zA-Z0-9]+$/',
        'token' => '/^[a-zA-Z0-9]+$/',
        'token_expiracion' => '/^[0-9]+$/',
        'imagen' => '/^[a-zA-Z0-9\.]+$/',
        'hash' => '//', // aqui iria la expresion regular que tiene el js
        'nombre_like' => '/^[a-zA-Z ]+$/',
        'modulo' => '/^[a-zA-Z ]+$/',
        'accion' => '/^[a-zA-Z ]+$/',
        'permiso' => '/^[a-zA-Z ]+$/',
        'monto' => '/^[0-9]+$/',
        'referencia' => '//',
        'comprobante' => '/^[a-zA-Z0-9 ]+$/',
        'estado' => '/^[a-zA-Z ]+$/',
        'stock' => '/^[0-9]+$/',
        'stock_min' => '/^[0-9]+$/',
        'stock_max' => '/^[0-9]+$/',
        'tabla_str' => '/^[a-zA-Z ]+$/',
        'monto_inicial_dolar' => '/^[0-9]+$/',
        'monto_inicial_bs' => '/^[0-9]+$/',
        'monto_final_dolar' => '/^[0-9]+$/',
        'monto_final_bs' => '/^[0-9]+$/',
        'key' => '/^[a-zA-Z ]+$/',
        'value' => '/^[a-zA-Z ]+$/',
        'codigo' => '/^[a-zA-Z0-9 ]+$/',
        'existencia' => '/^[0-9]+$/',
        'cantidad' => '/^[0-9]+$/',
        'broken' => '/^[0-1]+$/',
        'descripcion' => '/^[a-zA-Z0-9 ]+$/',
        'adicionales' => '/^[a-zA-Z0-9 ]+$/',
        'vip' => '/^[0-1]+$/',
        'sillas' => '/^[0-9]+$/',
        'imagen_name' => '/^[a-zA-Z0-9 ]+$/',
        'status' => '/^[a-zA-Z ]+$/',
        'titulo' => '/^[a-zA-Z ]+$/',
        'mensaje' => '/^[a-zA-Z ]+$/',
        'nro_orden' => '/^[0-9]+$/',
        'tipo' => '/^[a-zA-Z ]+$/',
        'tasa' => '/^[0-9]+$/',
        'permisos' => '/^[a-zA-Z ]+$/',
        'precio_compra' => '/^[0-9]+$/',
        'detalles' => '/^[a-zA-Z0-9 ]+$/',
        'razon_social' => '/^[a-zA-Z ]+$/',
        'documento' => '/^[0-9]+$/',
        'n_telefono1' => '/^[0-9]{10}$/',
        'n_telefono2' => '/^[0-9]{10}$/',
        'direccion' => '/^[a-zA-Z0-9 ]+$/',
        'metodo_pedido' => '/^[a-zA-Z ]+$/',
        'alias' => '/^[a-zA-Z ]+$/',
        'IVA' => '/^[0-9]+$/',
        'monto_final' => '/^[0-9]+$/',
    ];
    $GLOBALS['db1'] = [
        'host' => 'localhost',
        'name' => 'burgerhouse',
        'user' => 'root',
        'pass' => '12345'
    ];
    $GLOBALS['db2'] = [
        'host' => 'localhost',
        'name' => 'usuarios_burgerhouse',
        'user' => 'root',
        'pass' => '12345'
    ];
?>